trigger:
- master

pool:
  name: Default

steps:
- script: mvn -version
  displayName: 'Check Maven'

- script: |
    echo "User: $BROWSERSTACK_USERNAME"
  displayName: 'Debug'
  env:
    BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BStackConnection'
    browserstackLocal: true
    bsLocalOptions: |
      {
        "forceLocal": true
      }

- script: mvn clean install -DskipTests
  displayName: 'Install Dependencies'

- script: mvn test -P sample-test
  displayName: 'Run TestNG Tests'
  env:
    BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
    BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
